<!-- robot 根标签 -->
<robot name="carcamera" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--  camera 组件-->
    <!-- camera属性 -->
    <xacro:property name="camera_length" value="0.02" />
    <xacro:property name="camera_width" value="0.04" />
    <xacro:property name="camera_hight" value="0.04" />
    <xacro:property name="camera_mass" value="0.02" />
    <xacro:property name="joint_camera_x" value="${base_radius - camera_width}" />
    <xacro:property name="joint_camera_y" value="0.0" />
    <xacro:property name="joint_camera_z" value="${base_length / 2 + camera_hight / 2}" />

    <!-- 摄像头link -->
    <link name="camera_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_hight}"/>
            </geometry>
            <material name="camera_color">
                <color rgba="0 0.0 1 0.8"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_hight}"/>
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_hight}" />
        
    </link>
    <gazebo reference="camera_link">
        <material>
            Gazebo/Blue
        </material>
    </gazebo>

    <!-- 摄像头joint -->
    <joint name="cameralink2baselink" type="fixed">
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>
</robot>